import fs from 'fs';
const names = `house monitor tv film lightbulb lightbulb-off settings power volume-2 volume-1 volume-x play pause skip-forward skip-back
sun moon cloud cloud-rain cloud-sun cloud-moon cloud-lightning cloud-fog cloud-drizzle snowflake wind droplets mouse-pointer-2 keyboard
arrow-up arrow-down arrow-left arrow-right corner-down-left x check plus minus search chevron-right chevron-left chevron-down chevron-up
maximize minimize log-out user users link qr-code clock sunrise sunset moon-star sofa popcorn lamp bed utensils book-open cpu
memory-stick hard-drive monitor-off refresh-cw lock rotate-ccw send circle-dot wifi-off music hand move palette thermometer
external-link trash-2 copy info triangle-alert loader-circle ellipsis square rewind fast-forward list library clapperboard
bed-double sun-dim app-window mouse-pointer-click scan sliders-horizontal shield-check timer house-wifi zap tv-minimal monitor-play
gauge ticket square-arrow-out-up-right delete space type undo-2 maximize-2 hourglass circle-check star calendar captions video cctv bell`.split(/\s+/).filter(Boolean);
const out = {}; const missing = [];
for (const n of names) {
  const p = `node_modules/lucide-static/icons/${n}.svg`;
  if (!fs.existsSync(p)) { missing.push(n); continue; }
  const svg = fs.readFileSync(p, 'utf8');
  out[n] = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/\s+/g, ' ').trim();
}
fs.writeFileSync('../server/wwwroot/js/icons.mjs', '// Lucide icons (ISC), generated by tools/build-icons.mjs\nexport const ICONS = ' + JSON.stringify(out) + ';\n');
console.log('icons:', Object.keys(out).length, 'missing:', missing.join(' ') || 'none');
